apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    type: task
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
  selector:
    project: {{ .Release.Name }}

